apiVersion: external-secrets.io/v1 
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://192.168.1.30:8200/"
      path: "tokens/"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "multimediasaver"
          key: "token"
