apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multimediasaver-ingress
  namespace: multimediasaver
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multimediasaver-service
                port:
                  number: 80
