apiVersion: v1
kind: Service
metadata:
  name: multimediasaver-service
  namespace: multimediasaver
  labels:
    app: multimediasaver
spec:
  selector:
    app: multimediasaver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
